# Generated by Django 3.2.9 on 2021-11-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Text'), (2, 'Single choice'), (3, 'Multiple choice')], default=1)),
                ('answer', models.ManyToManyField(blank=True, to='survey.Answer')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_start', models.DateTimeField()),
                ('data_end', models.DateTimeField()),
                ('questions', models.ManyToManyField(blank=True, to='survey.Question')),
            ],
            options={
                'verbose_name': 'Survey',
                'verbose_name_plural': 'Surveys',
                'ordering': ['-data_start'],
            },
        ),
        migrations.CreateModel(
            name='SubmitSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_survey', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Submit survey',
                'verbose_name_plural': 'Submit surveys',
            },
        ),
        migrations.CreateModel(
            name='SubmitAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('answer_choices', models.ManyToManyField(blank=True, to='survey.Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('submit_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submit_answer', to='survey.submitsurvey')),
            ],
            options={
                'verbose_name': 'Submit answer',
                'verbose_name_plural': 'Submit answers',
            },
        ),
    ]
